---
title: "Popular Songs' Lyrics Analysis"
author: "Phong Duong"
date: "2024-02-14"
output: html_document
---

# Library

```{r}
library(tidyverse)
library(rvest)
library(xml2)
library(geniusr)
library(tidytext)
```

# Data Collection

## Test Scrape 2023

```{r}
billboard100_2023 <- "https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_2023"

read_html(billboard100_2023) %>% 
  xml_find_all("//table[contains(@class,'wikitable')]/tbody/tr[td]") %>% 
  xml_text() %>% 
  str_replace_all("\n", "") %>% 
  str_replace_all("\"", "%") %>% 
  as_data_frame() %>% 
  separate_wider_delim("value","%", names = c("position", "song_name", "artists"))
```

## Scrape All Songs

```{r}
years <- c(2019:2023) 

get_top_songs <- function(year){
  url <- paste0("https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_", year)
  
  df <- read_html(url) %>% 
  xml_find_all("//table[contains(@class,'wikitable')]/tbody/tr[td]") %>% 
  xml_text() %>% 
  str_replace_all("\n", "") %>% 
  str_replace_all("\"", "%") %>% 
  as_data_frame() %>% 
  separate_wider_delim("value","%", names = c("position", "song_name", "artists"))
  
  df <- df %>% mutate("year" = year)
  
  return(df)
}

all_top_songs <- map_dfr(years, get_top_songs)

all_top_songs
```

## Get Lyrics

```{r}
just_lyrics <- function(artist, song){
  id <- search_song(paste(song, str_extract(artist, "\\w+( [A-Z]\\w+)?")))[1,1] %>% pull()
  
  get_lyrics_id(id) %>% 
    .$line %>% 
    paste(., collapse= " ")
}

start <- Sys.time()
all_songs_lyrics <- all_top_songs %>% 
  mutate(
    lyrics = mapply(just_lyrics, artists, song_name)
  )
stop <- Sys.time()

write_csv(all_songs_lyrics, "all_top_songs_lyrics.csv")
```

It took 31 minutes to scrape so we save the data into a file to avoid scraping every time we commence the project.

# Data Cleaning

```{r}
all_songs_lyrics <- read.csv("all_top_songs_lyrics.csv") %>% 
  drop_na()

wrong_lyrics <- c("Ritmo (Bad Boys for Life)", "My Ex's Best Friend", "Hrs and Hrs")

all_songs_lyrics <- all_songs_lyrics %>% 
  filter(!song_name %in% wrong_lyrics) 
```

```{r}
songs_en <- all_songs_lyrics %>% 
  mutate(
    lang = cld3::detect_language(lyrics)
  ) %>% 
  filter(lang == "en")
```

# Sentiment Analysis

```{r}
sa_df <- songs_en %>% 
  unnest_tokens(word, lyrics) %>% 
  inner_join(get_sentiments("bing")) %>% 
  group_by(year, song_name, artists) %>% 
  count(sentiment) %>% 
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
  mutate(sentiment = positive - negative) %>% 
  mutate(sentiment_label = ifelse(sentiment == 0, "neutral", ifelse(sentiment > 0, "positive", "negative")))

sa_df
```

## Song sentiment over the years

```{r}
sa_count <- sa_df %>% 
  group_by(year, sentiment_label) %>% 
  count()

#ggalt for smooth lines
ggplot(sa_count) +
  ggalt::geom_xspline(aes(year, n, color = sentiment_label)) +
  xlab("year") +
  ylab("number of songs")
```

## Most positive vs most negative song

```{r}
most_pos <- sa_df %>% 
  group_by(year) %>% 
  slice_max(sentiment)

most_pos
```

```{r}
most_neg <- sa_df %>% 
  group_by(year) %>% 
  slice_min(sentiment)

most_neg
```

```{r}
ggplot() +
  geom_col(data = most_pos, aes(year, sentiment), fill = "orange") +
  geom_col(data = most_neg, aes(year, sentiment), fill = "blue") +
  coord_flip()
```

## Most common positive and negative words

```{r}
common_words <- songs_en %>% 
  unnest_tokens(word, lyrics) %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(word, sentiment, sort = TRUE)

common_words
```

```{r}
ggplot(common_words %>% filter(n > 100)) +
  geom_col(aes(reorder(word,n), n, fill = sentiment)) +
  coord_flip() +
  facet_wrap(~sentiment, scales = "free_y") +
  xlab("frequency") +
  ylab("word")
```

## Artists with most postive and negative songs

```{r}
sa_df %>% 
  group_by(artists) %>% 
  count(label = sentiment_label, sort = TRUE) %>% 
  head(5)
```
